AI:
  key1: Hogwarts
server:
  port: 8081
#  servlet:
#  connection-timeout: 18000000        这个只支持  spring-boot 2.1 6（junit 4） 版本以下,最新版本不支持
servlet:
  session:
  timeout: 30m #3Q分钟，测试的话时间不能太短，否则不准。m(分钟)， s(秒)， h(小时)， 不写单位默认毫秒
spring:   #这项配置一般都是spring-cloud 使用，用于区分哪个spring-boot
  application:
    name: aitest
  datasource:
   # url: jdbc:mysql://127.0.0.1:3306/Hogwarts-mini?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai  #allowMultiQueries=true 允许批量查询
    url: jdbc:mysql://192.168.31.105:3306/Hogwarts-mini?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai  #allowMultiQueries=true 允许批量查询
    username: root
    password: Jjpwd_0910
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hogwartsmini.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.hogwartsmini.demo.dao: debug #打印sql
map:
  local:
    env: 开发环境